# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0008_auto_20180131_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='login_registration_app.User')),
                ('playlists', models.ManyToManyField(related_name='favorite_songs', to='login_registration_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='item',
            name='playlists',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
