# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0010_auto_20180131_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='artist',
            new_name='creator',
        ),
    ]
