# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0011_auto_20180131_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='playlists',
            new_name='wishlists',
        ),
    ]
